FROM gisops/valhalla:latest_base as builder
MAINTAINER Nils Nolde <nils@gis-ops.com>

# this image will create all files & folder as the passed USER_ID & GROUP_ID
# beware: it _only_ works if the mapped folder exists before starting a container!

# what this does:
# we create a valhalla user with the specified user UID and group GID. that user will run the image. that user also creates files with 664/775 permissions so that the same group can also write. practically this means that all exposed files created during container startup will be editable by the user(s) with mathching user and/or group ID, be it on the host or inside the container. no more sudo if you don't want to. linux incrememnts user/group UIDs starting at 1000, so the admin user has 1000 user/group ID. if a user with another user/group ID is running this image, the mapped directory should not exist yet (or have 0775/0777 as permission bits), the container ideally creates it. otherwise the internal valhalla user doesn't have the permissions to write to the host user's directory and startup will fail.
# reference: https://jtreminio.com/blog/running-docker-containers-as-current-host-user/

ARG USER_ID=1000
ARG GROUP_ID=1000

# umask 002: create dirs with 775 (rwxrwxr-x) and files with 664 (rw-rw-r--)
# the entrypoint/cmd needs to be executed with bash in this case
RUN groupadd -g ${GROUP_ID} valhalla && \
  useradd -lmu ${USER_ID} -g valhalla valhalla && \
  install -d -m 0775 -o valhalla -g valhalla /custom_files_no_root && \
  echo "umask 0002" >> /etc/profile

COPY scripts/. /valhalla/scripts

USER valhalla

WORKDIR /custom_files_no_root

# Expose the necessary port
EXPOSE 8002
ENTRYPOINT ["/valhalla/scripts/run.sh"]
CMD ["build_tiles"]