# Builds a new image from Valhalla's "manually_triggered_build" image

name: manual image build
on:
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build latest image
        run: |
          sed -i "s/:latest/:manually_triggered_build/g" Dockerfile
          docker build -t ghcr.io/${{ github.repository }}/valhalla:manually_triggered_build .
          docker push ghcr.io/${{ github.repository }}/valhalla:manually_triggered_build
